name: 'block-day-from-calendar-secrets-action'
description: 'Setup cohorts current content (block.day) in env vars'
inputs:
  auth-client-email:
    description: 'google service account client email'
    required: true
  auth-private-key:
    description: 'google service account private key'
    required: true
  spreadsheet:
      description: 'spreadsheet document id'
      required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'lock'
  color: 'green'
